module.exports['ENV'] = {
  OPENTOK_API_KEY: 'INSERT YOURS',
  OPENTOK_SESSION_ID: 'INSERT YOURS',
  OPENTOK_TOKEN: 'INSERT YOURS',
  AZURE_FACE_API_ENDPOINT: 'INSERT YOURS',
  NEXMO_API_KEY: 'INSERT YOURS',
  NEXMO_API_SECRET: 'INSERT YOURSI',
  NEXMO_APPLICATION_ID: 'INSERT YOURS',
  NEXMO_PRIVATEKEY_PATH: './private.key',
  NEXMO_NUMBER: "INSERT YOURS",
  SITE_URL: 'https://domain.ext'
}
