module.exports['ENV'] = {
  OPENTOK_API_KEY: 'X',
  OPENTOK_SESSION_ID: 'X',
  OPENTOK_TOKEN: 'X',
  AZURE_FACE_API_SUBSCRIPTION_KEY: 'X',
  AZURE_FACE_API_ENDPOINT: 'X',
  NEXMO_API_KEY: 'X',
  NEXMO_API_SECRET: 'X',
  NEXMO_APPLICATION_ID: 'X',
  NEXMO_PRIVATEKEY_PATH: './X',
  NEXMO_NUMBER: 'X',
  SITE_URL: 'X'
}
